
- name: install grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_6.2.5_amd64.deb

- name: allow web traffic  
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: allow grafana
  ufw:
    rule: allow
    port: "3000"
    proto: tcp

- name: start and enable grafana
  service:
    name: grafana-server
    state: restarted
    enabled: yes

- name: add port redirect from http to grafana
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: "enp0s3"
    protocol: tcp
    match: tcp
    destination_port: "80"
    jump: REDIRECT
    to_ports: "3000"
    comment: redirect web traffic to port 3000
  become: yes

- name: install dependencies
  apt:
     name: "{{ packages }}"
  vars:
     packages:
      - iptables-persistent

- name: save forwarding rule
  command: netfilter-persistent save

